### ISSUE TITLE
weight_mask not exist

### ISSUE THREAD

**Issue by he-y** [jaeho-lee/layer-adaptive-sparsity#2]
Hi,
Thanks for the code.
Please see [this line](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/tools/pruners.py#L199), weight_mask not exist

**Comment by jaeho-lee** [comment]
Thank you for the comment. Could you let me know what version of Pytorch you are using, and whether you have already performed pruning on the target model? If you have not pruned the model already, then the tensors in the model will not have been "reparameterized," resulting in the 'not existing' error.

**Comment by he-y** [comment]
Thanks for the reply.
Pytorch version is 1.8.

From the [function in main.py](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/iterate.py#L63), and a few functions in pruners.py including [function1](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/tools/pruners.py#L11), [function2](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/tools/pruners.py#L48), [function3](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/tools/pruners.py#L166), [function4](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/tools/pruners.py#L199), I didn't find any code to conduct pruning. 

Please correct me if I miss something.
Thanks a lot!

Edit:
I didn't perform pruning on the target model.

**Comment by he-y** [comment]
Just find the model is loaded with [a special pruning operation](https://github.com/jaeho-lee/layer-adaptive-sparsity/blob/817dad7abc1bfebcfbad7ae00af253e557c8749b/tools/modelloaders.py#L69).
Problem solved. Thanks!
