### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by jp5488995** [jaeho-lee/layer-adaptive-sparsity#4]
First of all, I'd like to congratulate you for your amazing work!

I was wondering if you could comment on the Licence rights of this repo, as I see there is no file. Perhaps you could add a Licence to know what is the status ?

**Comment by jaeho-lee** [comment]
thanks for your interest!

unfortunately, i do not know much about standard forms for licenses or how to add them.
i have just googled some options, and the mit license looks great for this project.

i will be adding the license in a few days; meanwhile, feel free to use the code in the mit license style.
(that is, if i am correct, use it as you wish)

**Comment by Hrayo712** [comment]
Hi,

Thanks a lot for the clarification! indeed it would be very helpful if the MIT LICENCE file is added.

Thanks!

**Comment by jp5488995** [comment]
Hi,

Thanks a lot for the clarification @jaeho-lee ! indeed it would be very helpful if the MIT LICENCE file is added for my internal developments.

Looking forward :)

Thanks!

**Comment by jaeho-lee** [comment]
just added!
