### ISSUE TITLE
sorry i cannot actually understand the meaning of u and v in Figure 1, can you explain it easily?

### ISSUE THREAD

**Issue by xibici** [jaeho-lee/layer-adaptive-sparsity#5]
![image](https://github.com/jaeho-lee/layer-adaptive-sparsity/assets/46315437/2eadcc7b-2879-49f8-a5a9-e1731090cc4d)
u and v in Figure 1

can you explain it easily?thank you!!

**Comment by jaeho-lee** [comment]
hi--- thank you for your interest.

vectors u and v are a flattened, absolute-valued, and sorted version of the weight matrix at each layer.
(i wrote only 2 vectors for simplicity, but if there are L tensors then you'll have L vectors)

for example, suppose that we have a two-layer matrix with weights
W1 = [[-1,2],[3,-4]], W2 = [[-5,-6],[7,8]]
where Wi is the weight matrix of i-th layer.

then, u and v are:
u = [4,3,2,1], v = [8,7,6,5]

**Comment by xibici** [comment]
> hi--- thank you for your interest.
> 
> vectors u and v are a flattened, absolute-valued, and sorted version of the weight matrix at each layer. (i wrote only 2 vectors for simplicity, but if there are L tensors then you'll have L vectors)
> 
> for example, suppose that we have a two-layer matrix with weights W1 = [[-1,2],[3,-4]], W2 = [[-5,-6],[7,8]] where Wi is the weight matrix of i-th layer.
> 
> then, u and v are: u = [4,3,2,1], v = [8,7,6,5]

Thank you very much for the example!

**Comment by xuewengeophysics** [comment]
> hi--- thank you for your interest.
> 
> vectors u and v are a flattened, absolute-valued, and sorted version of the weight matrix at each layer. (i wrote only 2 vectors for simplicity, but if there are L tensors then you'll have L vectors)
> 
> for example, suppose that we have a two-layer matrix with weights W1 = [[-1,2],[3,-4]], W2 = [[-5,-6],[7,8]] where Wi is the weight matrix of i-th layer.
> 
> then, u and v are: u = [4,3,2,1], v = [8,7,6,5]

Hi. Thank you for your attention to my question.

Maybe, there are errors in the paper, 
![image](https://github.com/user-attachments/assets/79203007-0421-4671-946b-cee7963f2839)

![image](https://github.com/user-attachments/assets/172f4eef-3393-486c-a4a6-0a21168f271b)

According to my opinion, the right equations are as follows

![image](https://github.com/user-attachments/assets/08c54821-2440-4159-9fd1-d65c7bee58e3)

**Comment by jaeho-lee** [comment]
This is not an error. Both the original expression and the one that you suggested should work, technically.

In the above thread, I used descending order because that is what people usually use. For the formalisms in the paper, I used ascending order.

**Comment by xuewengeophysics** [comment]
> This is not an error. Both the original expression and the one that you suggested should work, technically.
> 
> In the above thread, I used descending order because that is what people usually use. For the formalisms in the paper, I used ascending order.

Thank you very much!

At first, I think the equation is inconsistent with the figure.

![image](https://github.com/user-attachments/assets/bfe8acb2-bdcb-49e3-9976-fedb36453be5)

According to the equation (1), if index = 1, but that does match the figure 1.
![image](https://github.com/user-attachments/assets/aa65a67e-5215-4957-bc27-0e6e29a61a20)

![image](https://github.com/user-attachments/assets/178def58-cb14-47d0-a532-9ef5c8bc6504)

After reading your explaination, I understand. 
Thanks!
